# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_num', models.CharField(max_length=10, verbose_name='考生号')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('color', models.IntegerField(verbose_name='色彩')),
                ('sketch', models.IntegerField(verbose_name='速写')),
                ('linedraw', models.IntegerField(verbose_name='素描')),
                ('total', models.IntegerField(verbose_name='总分')),
            ],
            options={
                'verbose_name': '考生信息',
                'verbose_name_plural': '分数数据库',
            },
        ),
    ]
